evo:
  mutation-rate: 0.2
  population-size: 20  # use even numbers
abc:
  number-of-solutions: 10  # use even numbers
  show-bees: False
  limit: 100

use-alg: evo  # 'evo' or 'abc'
stop-after: 500  # Number of epochs to run
scale: 1.0  # UI-Scale
fps: 60  # Lower this to slow everything down
