evo:
  mutation-rate: 0.2
  population-size: 20  # use even numbers
abc:
  number-of-solutions: 10  # use even numbers
  show-bees: True
  limit: 20

use-alg: abc  # currently only 'evo' is supported
stop-after: 200
scale: 1.0
fps: 10
